/*
 * @file 
 * All the texts used by the VisualScience app.
 *
 * Note: For searching users functionnalities, you have to check userlist.js
 */
 var vsText = {
 	activityPeriod: 'Period of activity',
 	addMoreUsers: 'Show More Users',
 	coauthors: 'Co-Authors',
 	comparisonInterface: 'Comparison Interface',
 	confAfterToday: 'The conference cannot be scheduled before current date and time.',
 	conferenceScriptNotLoaded: 'The script file for conferences is not yet to loaded. Please try again later.',
 	csvScriptNotLoaded: 'The script file for CSV export is not yet loaded. Please try again later.',
 	dbTooLargeError: 'Oops, the number of users is too large for your browser local storage. Each time it will be reloaded from the server. To solve this issue, change the localStorage capacity in the configuration of your browser.',
 	doubleCheckForm: 'Some errors were found in the form, please check your inputs.',
 	emailNotEnabled: 'The email field has to be enabled to use this function.',
 	enterValidEmail: 'Please enter a valid email address.',
 	errorSendingMail: 'There was a problem while sending the email. Please try again later.',
 	errorServerSendingMessage: 'An error occured on the server side while sending the message. Please contact the administrator if this happens again.',
 	fileErrorTitle: 'File Error',
 	insertOneRecipient: 'Please insert at least one recipient.',
 	journals: 'Journals',
 	livingscienceScriptNotLoaded: 'The scripts file for LivingScience are not yet loaded. This is may be due to the LivingScience server being unreachable. Please try again later.',
 	loadDBTitle: 'Loading Users Database',
 	loaginForMessages: 'Please login to be able to send messages.',
 	lsNoResult: 'The Living Science search succeeded, but no publication found.',
 	lsNoResultTitle: 'No LivingScience Results',
 	messageScriptNotLaoded: 'The script file for messages is not yet loaded. Please try again later.',
 	messageSent: 'Message Sent. Send again ?',
 	messageServerNotFound: 'Oops, cannot reach the mail server. Please contact the administrator.',
 	messageUnknownError: 'Oops, an unspecified error occured. Please contact the administrator.\n' + 'Status:',
 	nbPubs: 'N° Publications',
 	noSearchResult: 'No results found.',
 	noUser: 'No User',
 	optionsToShow: 'Choose fields to show',
 	pleaseLogin: 'Please login first.',
 	result: 'Result',
 	results: 'Results',
 	saveSearchTitle: 'Save a Search',
 	search: 'Search',
 	selectOneUser: 'Please select at least one user.',
 	selectTab: 'Select a tab...',
 	sendingFile: 'Progress: Sending File... Please Wait.',
 	statistics: 'Statistics',
 	titleError: 'You have to set a title.',
 	titleUserNameUndefined: 'No First or Last name',
 	topPublications: 'Top 3 Publications',
 	uploadError: 'Progress: Error ',
 	uploadNotSuccessful: 'Progress: Upload Unsuccessful. Please Try Again.',
 	uploadSuccess: 'File Successfully Uploaded ! You may select another one.',
 	userHasNoName: 'First name or last name missing for one or more selected users. Cannot start the LivingScience search.',
 	userList: 'User List',
 	users: 'Users',
 	waitLoadingDB: 'Loading the user database... This happens only the first time.',
 };
