/*
 * @file 
 * All the texts used by the VisualScience app.
 *
 * Note: For searching users functionnalities, you have to check userlist.js
 */
 var vsText = {
 	activityPeriod: 'Period of activity',
 	addMoreUsers: 'Show More Users',
 	coauthors: 'Co-Authors',
 	comparisonInterface: 'Comparison Interface',
 	confAfterToday: 'The conference should be set after today.',
 	conferenceScriptNotLoaded: 'The script file for conferences has failed to load. Please try again a bit later.',
 	csvScriptNotLoaded: 'The script file for CSV exportations has failed to load. Please try again a bit later.',
 	dbTooLargeError: 'Oups, the database of users is too large for your browser. This means that every time, we\'ll have to load it from the server. To solve this problem, change the localStorage capacity in the configuration of your browser.',
 	doubleCheckForm: 'Please double check the form as there seems to be some errors.',
 	emailNotEnabled: 'The email field has to be enabled to use this function.',
 	enterValidEmail: 'Please enter a valid email',
 	errorSendingMail: 'There was a problem while sending the email. Please try again later.',
 	errorServerSendingMessage: 'An error occured on the server side while sending the message. Please contact the administrator if this happens again.',
 	fileErrorTitle: 'File Error',
 	insertOneRecipient: 'Please insert at least one recipient.',
 	journals: 'Journals',
 	livingscienceScriptNotLoaded: 'The scripts file for LivingScience have failed to load. This is may be due to LivingScience being unreachable. Please try again later.',
 	loadDBTitle: 'Loading Users Database',
 	loaginForMessages: 'Please login to be able to send messages.',
 	lsNoResult: 'The Living Science search succeeded, but apparently it did not find any publication for this search.',
 	lsNoResultTitle: 'No LivingScience Results',
 	messageScriptNotLaoded: 'The script file for messages has failed to load. Please try again a bit later.',
 	messageSent: 'Message Sent. Send again ?',
 	messageServerNotFound: 'Please come back later, there is a problem with the server.(404)',
 	messageUnknownError: 'An error occured:\n' + 'Status:',
 	nbPubs: 'N° Publications',
 	noSearchResult: 'There is no result for your search.',
 	noUser: 'no User',
 	optionsToShow: 'Choose fields to show',
 	pleaseLogin: 'Please Login',
 	result: 'Result',
 	results: 'Results',
 	saveSearchTitle: 'Save a Search',
 	search: 'Search',
 	selectOneUser: 'Please select at least one user',
 	selectTab: 'Select a tab...',
 	sendingFile: 'Progress: Sending File... Please Wait.',
 	statistics: 'Statistics',
 	titleError: 'You have to set a title.',
 	titleUserNameUndefined: 'No First or Last name',
 	topPublications: 'Top 3 Publications',
 	uploadError: 'Progress: Error ',
 	uploadNotSuccessful: 'Progress: Upload Unsuccessful. Please Try Again.',
 	uploadSuccess: 'File Successfully Uploaded ! You may select another one.',
 	userHasNoName: 'You\'ve selected a user with no first name or last name. Thus the Living Science search is impossible.',
 	userList: 'User List',
 	users: 'Users',
 	waitLoadingDB: 'Please wait while we load the users database. No worries, it only happens the first time.',
 };
